name: Trigger Fork

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  trigger_work:
    runs-on: ubuntu-latest
    steps:      
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: trigger_fork
